name = "BinaryTreeAgda"
version = "0.1.0"
defaultTargets = ["binarytreeagda"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

[[lean_lib]]
name = "BinaryTreeAgda"

[[lean_exe]]
name = "binarytreeagda"
root = "Main"
